# Используем официальный образ AWS Lambda для Python 3.12 (судя по твоим логам)
FROM public.ecr.aws/lambda/python:3.12

# Копируем файл с зависимостями
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Устанавливаем библиотеки без сохранения кэша, чтобы сэкономить место
RUN pip install --no-cache-dir -r requirements.txt

# Явно копируем только нужные директории с кодом
COPY app/ ${LAMBDA_TASK_ROOT}/app/
COPY bot/ ${LAMBDA_TASK_ROOT}/bot/

# Если у тебя есть папка alembic или конфигурация (например, alembic.ini), раскомментируй строки ниже:
COPY alembic/ ${LAMBDA_TASK_ROOT}/alembic/
COPY alembic.ini ${LAMBDA_TASK_ROOT}/

# Указываем точку входа для Лямбды (путь до переменной handler, куда обернут FastAPI)
CMD ["app.main.handler"]